
export const LOAD_TWITTS_SUCCESS = 'LOAD_TWITTS_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_TWITT_SUCCESS = 'CREATE_TWITT_SUCCESS';
export const UPDATE_TWITT_SUCCESS = 'UPDATE_TWITT_SUCCESS';

